[package]
name = "networked_kvs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["full"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio-util = { version = "0.7.14", features = ["codec"] }
futures = "0.3.31"